/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hijiri' at '16/07/13 0:15' with Gradle 2.14
 *
 * @author hijiri, @date 16/07/13 0:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
